# Задание 1

import numpy as np

In [4]:
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [7]:
mean_a = np.array([np.mean(a[:,0]), np.mean(a[:,1])])
mean_a

array([2. , 8.4])

# Задание 2

In [9]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание 3

In [15]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:, 1])
N = a.shape[0]
a_centered_sp/(N-1)

5


2.0

# Задание 4

In [21]:
a_t = np.transpose(a)
a_cov = np.cov(a_t)
a_cov[0,1]

2.0